name: Archive clickhouse code

on:
  push:
    branches: [ $default-branch ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: ["clang-11", "clang-11-aarch64"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install
      run: python -m pip install -U
    - name: Get clickhouse code
      run: |
        git clone --recursive https://github.com/ClickHouse/ClickHouse.git
        cd ClickHouse
        git checkout v20.12.3.3-stable
        git submodule update
    - name: Build clickhouse binary
      run: |
        cd docker/packager/
        mkdir dist
        ./packager --package-type binary --output-dir dist/ --compiler ${{ matrix.compiler }}
    - uses: actions/upload-artifact@v2
      with:
        name: dist
        path: ClickHouse/docker/packager/dist/
