name: Build clickhouse image

on:
  push:
    branches:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: ["clang-11", "clang-11-aarch64"]
    steps:
      - name: Maximize build disk space
        uses: easimon/maximize-build-space@ad3a54f8b164ae1b4e13a7e20e5a575e2ec1247f
        with:
          remove-dotnet: true
          remove-android: true
          remove-haskell: true
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Get clickhouse code
        run: |
          git clone https://github.com/ClickHouse/ClickHouse.git
          cd ClickHouse
          git checkout v20.12.3.3-stable
          git submodule update --init --recursive
      - name: Cache ccache
        uses: pat-s/always-upload-cache@v2.1.3
        env:
          cache-name: ccache
        with:
          path: ~/.ccache
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.compiler }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Build clickhouse binary
        run: |
          cd ClickHouse/docker/packager/
          mkdir dist_${{ matrix.compiler }}
          ./packager --package-type binary --output-dir dist_${{ matrix.compiler }}/ --compiler ${{ matrix.compiler }}
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: ClickHouse/docker/packager/dist_${{ matrix.compiler }}/
